name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-artifacts
        path: |
          bin/Release/
          obj/Release/
        retention-days: 30

  publish:
    needs: build-and-test
    runs-on: windows-latest
    if: github.event_name == 'release'
    permissions:
      contents: write   # ✅ allow writing release assets
    
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish Windows x64
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true
      
    - name: Create release package
      run: |
        $version = "${{ github.event.release.tag_name }}"
        $packageName = "SPRDNVEditor-$version-win-x64"
        mkdir $packageName
        Copy-Item "bin/Release/net6.0-windows/win-x64/publish/SPRDNVEditor.exe" "$packageName/"
        Copy-Item "README.md" "$packageName/"
        Copy-Item "LICENSE" "$packageName/" -ErrorAction SilentlyContinue
        Compress-Archive -Path "$packageName" -DestinationPath "$packageName.zip"
      shell: powershell
      
    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        files: SPRDNVEditor-${{ github.event.release.tag_name }}-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-quality:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Run code analysis
      run: dotnet build --no-restore --verbosity normal /p:TreatWarningsAsErrors=false
